In [3]:
import L3RM.L3RM
from L3RM.utils import *

In [4]:
d1 = first_order_derivative_filter(3,1)
d2 = first_order_derivative_filter(3,-1)

print(d1)
print(d2)

[[-1.  1.  0.]
 [ 0. -1.  1.]
 [ 0.  0. -1.]]
[[-1.  0.  0.]
 [ 1. -1.  0.]
 [ 0.  1. -1.]]


In [8]:
print(d1.T @ d1)
print(d2.T @ d2)

[[ 1. -1.  0.]
 [-1.  2. -1.]
 [ 0. -1.  2.]]
[[ 2. -1.  0.]
 [-1.  2. -1.]
 [ 0. -1.  1.]]


In [9]:
print(d1.T @ d1 + d2.T @ d2)

[[ 3. -2.  0.]
 [-2.  4. -2.]
 [ 0. -2.  3.]]


In [16]:
tm = np.random.randn(3,3)
tvec = np.reshape(tm,-1)
print(tm)

D1 = first_order_derivative_filter(9,3)
print(D1)

[[-0.73536141  0.79241418 -0.57288897]
 [-0.485019    1.36101778  0.69426766]
 [-1.80637019  1.19442553  0.9154067 ]]
[[-1.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0. -1.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0. -1.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0. -1.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. -1.]]


In [17]:
print(d1 @ tm)
print(np.reshape(D1 @ tvec, (3,3)))

[[ 0.2503424   0.5686036   1.26715664]
 [-1.32135119 -0.16659225  0.22113903]
 [ 1.80637019 -1.19442553 -0.9154067 ]]
[[ 0.2503424   0.5686036   1.26715664]
 [-1.32135119 -0.16659225  0.22113903]
 [ 1.80637019 -1.19442553 -0.9154067 ]]
